### ISSUE TITLE
In-Game Editing Gui

### ISSUE THREAD

**Issue by TehNut** [TehNut/GoodyBags#1]
Allow editing in-game by dropping items in slots.

**Comment by TehNut** [comment]
@BBoldt texture/concept? :D

**Comment by BBoldt** [comment]
![](http://i.imgur.com/wH2W5ua.png)

**Comment by TehNut** [comment]
PERFECT

**Comment by BBoldt** [comment]
![](http://i.imgur.com/FfXVfzJ.png)

**Comment by BBoldt** [comment]
from concept to texture just like that

**Comment by BBoldt** [comment]
wait I should probably separate the area for player inventory a bit more

**Comment by BBoldt** [comment]
![](http://i.imgur.com/KczegXr.png)

**Comment by BBoldt** [comment]
masterpiece

**Comment by TehNut** [comment]
Also needs text fields for all the texty stuff. And a button for "GO MAKE BAG"

**Comment by BBoldt** [comment]
how big should text field be?

**Comment by BBoldt** [comment]
![](http://i.imgur.com/Mndp9iP.png)

**Comment by TehNut** [comment]
Project dropped
