### ISSUE TITLE
Support for NBT

### ISSUE THREAD

**Issue by TehNut** [TehNut/GoodyBags#3]
Spawning tools with custom damages, machines that are based on NBT (looking at you Mekansim), or even Monster Spawners.

**Comment by TehNut** [comment]
Just going to drop [this](https://github.com/TGMP/ModularArmour/blob/master/src/main/java/chbachman/armour/util/json/CustomNBTJson.java) here

**Comment by Thiana** [comment]
+1 This would be lovely for giving things like starter tinker's tools.

**Comment by TehNut** [comment]
Project dropped
