### ISSUE TITLE
goody bag in binnie's mods compartment ruins life on this planet

### ISSUE THREAD

**Issue by BBoldt** [TehNut/GoodyBags#4]
"Looks like the Goodie Bag in a Binnies Core Compartments will crash the client if shift is held and the mouse moves over the bag. Or so Saice is reporting." http://paste.atlauncher.com/view/f21d047d

I cut out the crash report so you don't need to go through the entire log:
https://gist.github.com/07149e98a36bcc332b0f

**Comment by TehNut** [comment]
The fuck is Binnie doing...

What's the item inside the bag?

**Comment by BBoldt** [comment]
https://gist.github.com/432b4ac573ba2a1b50ff

books and books and books

**Comment by TehNut** [comment]
And what is ***the*** item? >.>

**Comment by TehNut** [comment]
Project dropped
