### ISSUE TITLE
Like half of the stuff I try to put in a goody bag causes errors

### ISSUE THREAD

**Issue by BBoldt** [TehNut/GoodyBags#8]
Things that cause errors, from flaming invalid bags, to the shift to view contents thing not working.

https://www.dropbox.com/s/gledaxrqhrnoatf/GoodyBags.zip?dl=0

All in separate json files, from various different mods. I don't know why the bags hate these specific items so much.

Also, here is what the working one looks like, I had to trim it down a lot:
https://gist.github.com/0771147d1e89983a05e0

**Comment by TehNut** [comment]
Project dropped
